import CryptoKit
import Foundation

guard CommandLine.arguments.count == 4 else {
    throw NSError(domain: "EmbedSkill", code: 1, userInfo: [
        NSLocalizedDescriptionKey: "Usage: EmbedSkill <SKILL.md> <Info.plist> <output.swift>",
    ])
}

let skill = try Data(contentsOf: URL(fileURLWithPath: CommandLine.arguments[1]))
let plist = try Data(contentsOf: URL(fileURLWithPath: CommandLine.arguments[2]))
let output = URL(fileURLWithPath: CommandLine.arguments[3])
let plistDigest = SHA256.hash(data: plist).map { String(format: "%02x", $0) }.joined()

// Including the plist digest makes privacy metadata edits trigger recompilation and relinking too.
let source = """
// Generated by EmbedSkillPlugin. Edit skills/apple-calendar-cli/SKILL.md instead.
enum EmbeddedAgentSkill {
    static let base64 = "\(skill.base64EncodedString())"
    static let infoPlistDigest = "\(plistDigest)"
}

"""
try source.write(to: output, atomically: true, encoding: .utf8)
